# docker-compose.yml
services:
  letters:
    build: .
    container_name: welcome-letter
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app/config/default-config.php:/var/www/welcome-letters/app/config/default-config.php:ro
      - ./app/config/letter-config.php:/var/www/welcome-letters/app/config/letter-config.php:ro
      - ./app/config/letter-functions.php:/var/www/welcome-letters/app/config/letter-functions.php:ro
      - ./app/templates:/var/www/welcome-letters/app/templates:ro
    environment:
      TZ: America/Chicago
